### ISSUE TITLE
ssb-chess-db kills sbot

### ISSUE THREAD

**Issue by frankiebee** [Happy0/ssb-chess-db#1]
hey [@happy0](@RJ09Kfs3neEZPrbpbWVDxkN92x9moe3aPusOMOc4S2I=.ed25519)  i want to play around ssb-chess and when i was trying to enable the plugin `ssb-chess-db` i get this error:
```
/node_modules/scuttlebot/plugins/plugins.js:187
        throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
        ^

Error: plugin at:ssb-chess-db expected name:chess-db but had:ssbChessIndex
```

in sbot

**Comment by Happy0** [comment]
Hullo! There's a workaround for this documented here: https://github.com/ssbc/patchbay#harder-install-full-dev-setup .

Feel free to keep this issue open - obviously it would be better to fix it properly. I don't have time to look into it just now, but I'll put it on my mental 'todo' list for when I do.

**Comment by Happy0** [comment]
```
After that you need to make sure that .ssb/config reads: "ssb-chess-db": "ssbChessIndex" for chess to work.
```

The workaround is to rename the `ssb-chess-db` key in `~/.ssb/config` to `ssbChessIndex`.

**Comment by Happy0** [comment]
Or if scuttlebot is running within your scuttlebutt application, you don't need the workaround - you can just add it as a plugin using .`use`. Like this:

https://github.com/ssbc/patchbay/blob/243dc738c8a3bb3083cc0b69bd8e4585c4b2e87c/background-process.js#L17
